### ISSUE TITLE
It still works fine?

### ISSUE THREAD

**Issue by ghost** [CYRIAQU3/ScrapTF-auto-raffle#1]

**Comment by Ciriak** [comment]
Hello, didnt you get any captchat ? I "stopped" the project because some Google captchat appear sometime when you tried to join a raffle.

(Sry for the weird english :p)

**Comment by ghost** [comment]
Haha your english is fine and no, no captchat or capture or anything to verify I wasnt using a script. It did time out sometimes but other then that it worked fine.

**Comment by ghost** [comment]
One thing I have noticed is that if there is over about 200-300 raffles then it will get to about the 50th one and then just not load anymore raffles. It will go all the way to the top of the page and just sit there and do nothing even after a page reload it will show raffles then instantly go blank to the top.

**Comment by shaunidiot** [comment]
Still working for me, fyi :)

Same problem as @seiterseiter. It won't fully enter all raffles. Only some of the raffles, for eg, 40/200 then all the raffles are gone (possibly not visible).

**Comment by ghost** [comment]
I usually get it to work again by disabling the script then turning it back on and it works again.

**Comment by Ciriak** [comment]
The script "hide" the raffle already entered for forcing the loading of the others.
Sometime ScrapTF stop sending more raffle, thats why i added a timer (30 sec) who reload the fully page.

Thanks for reporting the problem of "some raffles joined", i will check that soon.

If there is not more captchat i will reopened the project.

(But again, beware of bannishment !!! )

**Comment by ghost** [comment]
.
